### PR TITLE
Fixed And Added Small Chnages

### PR DESCRIPTION
**Pull request by Virusdb**
add a this will come soon to guides
fixed some stuff in readme

### CODE REVIEW

**Comment by Whirl21** [comment]
@Virusdb 👀 
there might be more such things so yea if you could make another one with all typos and stuff fixed ?
or this is all you found?

**Comment by Virusdb** [comment]
@Whirl21 you online rn?
Pls check you discord dms also merge this

**Comment by Whirl21** [comment]
aight np :)
i'll merge this ty

**Review by Whirl21 — COMMENTED** [review]
checked later

**Pull request merged**
